### ISSUE TITLE
export CV format txt/html

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1173]
Users would like to get a list of their papers to copy paste them in word documents.

Example in legacy: http://old.inspirehep.net/search?ln=en&ln=en&p=a+witten&of=hcv&action_search=Search&sf=earliestdate&so=d&rm=&rg=25&sc=0

 

Add another format in the dropdown menu under LaTeX(US) called 'CV format (html)' in 'Cite' and 'Cite all' that exports a paper in the following format:

For https://inspirehep.net/literature/1781327

Geodesics of the hyperbolically symmetric black hole
L. Herrera, A. Di Prisco, J. Ospino, L. Witten
arXiv:2002.07586 [gr-qc]
10.1103/PhysRevD.101.064071
Phys.Rev. D101 (2020) no.6, 064071

where title, authors, arxiv, doi are links.

The fields should be:
Title <linked>
Authors as they appear in the search results with et al. <linked>
arxiv id <linked> [arxiv category]
doi <linked>
pub note

(jira issue: [INSPIR-3635](https://its.cern.ch/jira/browse/INSPIR-3635))

**Comment by StellaCh** [comment]
In legacy, we have different options for txt and html formats, let's brainstorm on ways we could have them both in 1 option.

**Comment by harunurhan** [comment]
- We need to add new formats `text/html`, `text/plain`, for literature detail and list endpoints, similar to https://github.com/inspirehep/inspirehep/blob/276bd2e2eaca0f576c0cf7398daa67236c2f6c4b/backend/inspirehep/records/config.py#L103-L116
 For search endpoints, `_source` should be specified for the new formats so that only required fields retrieved from `elasticsearch`.
  - (Not sure if we want to generate also these formats on index time)
- We can use `jinja` templates serialize records to these formats.
- New formats should be added [here](https://github.com/inspirehep/inspirehep/blob/master/ui/src/literature/constants.js), so that they are visible on the UI.
- [This](https://github.com/inspirehep/inspirehep/blob/276bd2e2eaca0f576c0cf7398daa67236c2f6c4b/ui/src/literature/citeArticle.js#L6) shouldn't prefix `application` anymore but receive the full `mime-type` 
- When the format is `text/html`, [this](https://github.com/inspirehep/inspirehep/blob/master/ui/src/literature/components/CiteModalAction.jsx#L114) should use `SanitizedHTML` instead, which allows only limited number of tags and attributes (similar to [Banner.jsx](https://github.com/inspirehep/inspirehep/blob/276bd2e2eaca0f576c0cf7398daa67236c2f6c4b/ui/src/common/layouts/Header/Banner.jsx#L45-L50))

**Comment by monaawi** [comment]
To keep track of the issues to fix:

- multiple affiliations for authors - 'and' needs spaces
- add check for authors existing when there are collaborations but not authors -> https://sentry.inspirebeta.net/inspire-qa/hep/issues/394605/?query=is%3Aunresolved
- spacing between records in the cite all
- middle dot between collaborations and authors needs space
- https://inspirebeta.net/literature/1688995 missing collaboration

**Comment by StellaCh** [comment]
LGTM, just one comment to change the title of the dropdown to "CV (html)"
