### ISSUE TITLE
Move `ui-tests` to cypress

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1200]

**Comment by harunurhan** [comment]
## Required records

(There should be single script to clear DB, and insert records that are needed for ui-tests)

### author detail
- author (better to have experiment and institution data)
- publications
- citations

### literature detail
- one of the author's publication can be used, since it will have citations as well
- a seminar

### seminar detail
- the seminar for the literature detail can be used

### conference detail
- conference
- contributions

### institution detail
- author's institution can be used, since it will have publications of the author

### experiment detail
- author's experiment or another experiment
- papers incase of another experiment is used

### job detail
- job

### search pages
- All the data for the detail pages should be more or less enough for the literature search
- For the rest we should insert more records

### submissions
- For the update forms, records for the details pages can be used


## cypress screenshot testing

https://github.com/palmerhq/cypress-image-snapshot can be used

## CI

It would be better to move ui-tests from travis, to Circle CI where we run the whole infra (db, web server, worker, elasticsearch etc.) for `e2e` anyway. And at the end we will be moving `e2e` tests into the same suite, once we have time to port them to `cypress`
