### ISSUE TITLE
Create journal dict for refextract

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1289]
Move the `kb` file creation in a cronjob to hep https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/refextract/tasks.py#L35 

**TECH**
On hep create a function`create_journal_dict` which will:
1. Create a query which will gather all journal titles and short titles from db. The query should use SQLAlchemy ORM and the content should be the same as in [this queries](https://github.com/inspirehep/inspire-next/blob/5120677b03611764c4f9d2ea0087f60cd41b93a2/inspirehep/modules/refextract/tasks.py#L51-L70).
2. Use gathered data to populate dict as in [here](https://github.com/inspirehep/inspire-next/blob/5120677b03611764c4f9d2ea0087f60cd41b93a2/inspirehep/modules/refextract/tasks.py#L73-L86).
3. Return the dict.

**Comment by harunurhan** [comment]
Legacy approach of passing input via file is inefficient and unnecessary in this case. So we should just modify `refextract` API to accept the input simply as a function param. In this way, we don't need to deal with writing file over the network and scheduling a cron job etc.

**Comment by michamos** [comment]
That should work well. The task to write the journal KB to disk is fast (<1s for the whole task) so we should be able to do the request on the fly and pass the data to refextract. If we use the SQLAlchemy ORM instead of the handwritten requests in https://github.com/inspirehep/inspire-next/blob/11dcad6d3ecf6f5b5457b1af014121c73c1dcc3e/inspirehep/modules/refextract/tasks.py#L51-L69, we should get caching at the SQLAlchemy session level (so a new query in the same session won't hit the DB).

**Comment by harunurhan** [comment]
We need pass not a dict but a list of dict that is similar to below right? @michamos 

```
[{ short_title, journal_title, title_variant }]
```

Also what I don't get from this task is that we just port the function from `next` and that's it? Not even use it anywhere yet?

**Comment by michamos** [comment]
no, you need to pass a `dict`, that maps all possible values in all journals as follows:
* `short_title` -> `short_title`
* `journal_title` -> `short_title`
* `title_variant` -> `short_title`
This is what's happening in https://github.com/inspirehep/inspire-next/blob/5120677b03611764c4f9d2ea0087f60cd41b93a2/inspirehep/modules/refextract/tasks.py#L73-L86 (but using a python `dict` rather than the special writer).
 The problem with a list is that ordering is relevant for equality, so you would need to sort it first, which is not really efficient.

**Comment by michamos** [comment]
The function needs to be called every time you call the refextract API. So currently only in the editor views (`extract_references_from_string`, `extract_references_from_url`).

**Comment by harunurhan** [comment]
There is no mention of caching here? Is it a plan for after?

**Comment by michamos** [comment]
caching is implemented inside `refextract`, the caller doesn't have to know about it, I'm just giving a bit more context here.
