### ISSUE TITLE
Update author on labs

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/inspirehep#1347]
Currently, when we update an author, a bibedit holdingpen entry is created. This should be handled by labs.
Requirements are in:
https://docs.google.com/document/d/1OdeisaNXd1XSvKo_GCBxS0nIUE9gmryViwmANoMP1Bk/edit#

**Tech Notes**:
* Modify the author submission [views put](https://github.com/inspirehep/inspirehep/blob/d524f1fe523b61da6d3e47ea678eccd56b91a5a4/backend/inspirehep/submissions/views.py#L107). Currently it is calling next to start a workflow. It will need to look similar to Jobs put views.
    * Add a check to make sure the user has the right permissions to edit this author. (Similar to [can_user_edit](https://github.com/inspirehep/inspirehep/blob/d524f1fe523b61da6d3e47ea678eccd56b91a5a4/backend/inspirehep/accounts/api.py#L28)) (same orcid). Need to verify: should we compare current author orcid with ids->orcid or acquisition_source->orcid? We think it is ids->orcid
    * Then, just call record update and create an rt ticket as specified in the google doc
* We need to add a ```can_edit``` field to the ```AuthorsBaseSchema```. It should return true for catalogers or user with orcid same as in ```acquisition_source```. 
* In the authors ```DetailPageContainer```, render the ```EditRecordAction``` normally only if ```can_edit``` is true. Otherwise, we will need to have a popup - discuss with Stella how exactly it should look.
* Rename the ```Comments``` [field label](https://github.com/inspirehep/inspirehep/blob/d524f1fe523b61da6d3e47ea678eccd56b91a5a4/ui/src/submissions/authors/components/AuthorForm.jsx#L308) in the ```AuthorForm``` to ```Comments to the INSPIRE team```
* We need to create an ```AuthorSubmissionPage``` with the message from the google doc. The backend put endpoint will also need to be modified to send the author control_number. This should only be used for the [redirect](https://github.com/inspirehep/inspirehep/blob/d524f1fe523b61da6d3e47ea678eccd56b91a5a4/ui/src/submissions/index.jsx#L78) with  from={`${SUBMISSIONS_AUTHOR}/:id/success`} as it is only for updates.

* We need to check for fields like institutions, experiments and advisors as it is now allowed for them to be deleted. A similar check is done in ```get_updated_record_data```
* Add hidden fields to authors schema for ```advisors```, ```positions``` and ```project_membership```. Update the builders with the hidden flag as well.
- Handle the new hidden field in the author marshmallow loader as well (same way as we handle hidden email addresses). Use ```NonHiddenRaw```.
- Hide hidden fields in the ```AuthorPublicSchema```.
- Add hidden checkboxes in the ```AuthorForm``` with a ```LabelWithHelp``` with the tooltip from the google doc. 
- Will need to use an```ArrayOf``` without the ```MinusCircleOutlined``` for those fields. We don't want the option to remove them.
- Add hidden also to ui authors schema
- Add the description from the google doc in the ```AuthorForm``` under Career Info.

**Comment by drjova** [comment]
add a hide button and remove the remove button for those fields

**Comment by harunurhan** [comment]
AFAIR, latest decision was

- Have `hidden` fields for those fields
- `delete` buttons will be only displayed for catalogers from now on.
- `hidden` fields should have tooltip, similar to "Please add a comment if you would like to delete"

**Comment by StellaCh** [comment]
the latest decision is also in the [gdoc](https://docs.google.com/document/d/1OdeisaNXd1XSvKo_GCBxS0nIUE9gmryViwmANoMP1Bk/edit#)

**Comment by monaawi** [comment]
https://github.com/inspirehep/inspirehep/pull/1498/files  - contains the changes for the authors put view (it is not going through a workflow anymore), the rt ticket, the can_edit logic, the new update success page and renaming fields in the update form.

**Comment by harunurhan** [comment]
here are the steps thare 

- Cherry-pick the commit from https://github.com/inspirehep/inspirehep/pull/1498
- Fix comments
- Add `hidden` subfield to `advisors`, `project_membership`, `positions` fields of `authors` schema on `inspire-schemas`
- Also make sure that `AuthorBuilder` methods for those fields takes and sets `hidden` property.
- Change author form schema for those field to accept `hidden` subfield https://github.com/inspirehep/inspirehep/blob/e695817f2430667086ce9bfe9b48996ffa05ba38/ui/src/submissions/authors/schemas/author.js#L59-L96
- Add `hidden` boolean form field for https://github.com/inspirehep/inspirehep/blob/e695817f2430667086ce9bfe9b48996ffa05ba38/ui/src/submissions/authors/components/AuthorForm.jsx#L170-L305. An example in the same form: https://github.com/inspirehep/inspirehep/blob/e695817f2430667086ce9bfe9b48996ffa05ba38/ui/src/submissions/authors/components/AuthorForm.jsx#L96-L108. This example also shows how to render help tooltip.
- Add `allowItemDelete` prop to `ArrayOf` component which hides the delete button, and true by default
- Set `allowItemDelete` based on current user's roles. Basically `allowItemsDelete={isCatalogerLoggedIn}`
- Form serializers shouldn't need to be changed, since we pass form data for directly to the builder for these fields.
- Modify e2e test for author submission to use these hidden fields
  - Optionally write a e2e test case for a user, updating her own author record, and another use CAN't update it (no "Edit" button) 

For any details (possibly for exact requirements, refer main issue comment)

**Comment by StellaCh** [comment]
Position of the hidden checkboxes:
<img width="606" alt="Screenshot 2020-11-04 at 10 27 49" src="https://user-images.githubusercontent.com/24955201/98093881-d00f9600-1e88-11eb-881a-d8b2f275d48f.png">

**Comment by MJedr** [comment]
Here is the PR for inspire-schemas https://github.com/inspirehep/inspire-schemas/pull/410
