### ISSUE TITLE
localStorage versioning 

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1359]
**Describe the bug**
Sometimes when you try to download a format (i.e. bibtex) of a record,  you get `406`.  We should start versioning the localStorage to avoid these errors in the future.

**Comment by drjova** [comment]
![image](https://user-images.githubusercontent.com/4287772/94126985-a2323d00-fe58-11ea-86ae-886c1c23cc8f.png)

**Comment by harunurhan** [comment]
The bug is fixed in #1361 temporarily. I'll check how we can do proper local storage versioning, migrations and cleanup without a lot of effort. 

This could be a good time to investigate if we need to move `IndexDB`, because AFAIR we were seeing errors like "Local storage limit exceeded" from some clients.

**Comment by harunurhan** [comment]
Since we just need a simple `key -> value` store, `IndexedDB` is an overkill unless we use a simple wrapper like https://github.com/localForage/localForage which also comes with `version` support.

If the library size is too big, we can just write a simple wrapper that clears whole `localStorage` when version is changed.

**Comment by karolina-siemieniuk-morawska** [comment]
TECH NOTES: Implement localForage, write function to loop through localStorage to get values and set them in localForage in order to persist user settings (to be deleted after most of the users use the app at least once), replace localStorage in storage.js file with localForage

**Comment by michamos** [comment]
did you see my concern regarding Safari compatibility in https://cern-rcs-sis.zulipchat.com/#narrow/stream/310485-inspire/topic/localstorage/near/278165924 ?

**Comment by drjova** [comment]
the library fallback to localStorage if it's not supported
