### ISSUE TITLE
Handle versions for optimistic concurrency control in editor/REST endpoints

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1387]
When making changes to a record, it might happen that in the meantime, a concurrent transaction has made a different change to the same record. 

The way things are done currently, those modifications will be silently overwritten by the most recent transaction to be committed to the database (nothing catastrophic is happening though due to legacy version checks). The `RecordsMetadata` model uses versioning for optimistic concurrency control: SQLAlchemy maintains a version counter, which is forced to monotonically increase. In case a transaction tries to lower the version counter (as would happen if the record to be modified was read at an earlier version), an exception is raised.

We should expose this feature to the REST APIs and editor to make sure we don't silently overwrite data.

**Comment by harunurhan** [comment]
Also for submissions that does immediate updates (without approvals)

**Comment by harunurhan** [comment]
A cataloger did "important" editing and meanwhile a new update came in, so SAVE would fail for the cataloger. They could refresh to get the new version but then they would lose all the work. I think we have to address this issue.

@michamos

**Comment by michamos** [comment]
At some point we had the idea of using the merger to combine the two update and the edit, but that would be a lot of work to implement. As a first step, we can just fail the save with a clear message of what to do, then improve the UX if it happens often.

**Comment by harunurhan** [comment]
How about doing a simple diff on top level fields if different fields modified just accept the change instead of failing? Is there problem with that?

**Comment by harunurhan** [comment]
Invenio is "supposed" to implement this anyway via https://github.com/inveniosoftware/invenio-records-rest/blob/896a34e47f3a1eab036c89d6348f59c2679fba86/invenio_records_rest/views.py#L883.

Etag check logic is here: https://github.com/inveniosoftware/invenio-rest/blob/0322ce1d63a6f1736bcc4dc0928c9336b96ae0e1/invenio_rest/views.py#L250-L285

This doesn't work because:
1. Invenio is returning `record.version_id` for GET but passing `record.revision_id`. Maybe this is how it is supposed work, but I have some doubts, because it seems like `revision_id = version_id + 1`, and they are maintained differently I guess.
2. Nginx servers compressed json with weak `eTag` even if it is strong, however invenio is checking eTag with `weak=False`
3. Let's assume all these works, we do have a custom `eTag` https://github.com/inspirehep/inspirehep/blob/8694625b451ce6cfb52d8bf42dc24460e9a731af/backend/inspirehep/records/serializers/response.py#L33. But we can use the default `invenio` `eTag` (`version_id`) and add `vary: Content-Type` header instead of using content type aware `eTag`.

Concerns:

1. Implementing this on REST endpoints, may require some ugly and complicated `invenio` workarounds. 
2. Do we want to also implement this `record.update` level, or `REST` only?
3. Do we want to make it really secure? Since version is are simply auto-incremented integers it is easy to guess the next version and overwrite it via `PUT` anyway.

**Comment by harunurhan** [comment]
- Looks like the easiest way is fork `invenio-records-rest` just to fix `eTag` check, by calling `check_etag(etag_that_we_return_wiht_get, weak=True)`
- We should return same `eTag` from `GET /api/editor/<collection>/<id>` too.
- Optionally we can use also change how set `eTag`, use `revision_id` only and leverage `vary` header.
- `record.update` already works and gives `StaleDataError`
