### ISSUE TITLE
Disambiguation II - exact match authors from paper

### ISSUE THREAD

**Issue by pazembrz** [inspirehep/inspirehep#1419]
Take a record id from disambiguation queue and match every author (unmatched - without $ref). For each of those, search its IDs (similar to the exact match in the workflow).
If there will be exact match then store $ref to this author in literature record.

*TECH*:

* Create a celery task which will be triggered on [record commit](https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/records/receivers.py#L18)
* For each authors, search its IDs and emails in author records (similar to the exact match in the workflow). If there's only one result, assign the signature to that author by adding `record.$ref`

**Comment by michamos** [comment]
I'm reading this only now and wasn't there at the refinement, but what's the reason for not simply using celery tasks for each record like we do for indexing?

**Comment by drjova** [comment]
The problem with the celery task is when to trigger it, we're indexing the record and adding a task for disambiguation (which will add  `$ref`) will mean that we might have a race condition and we end up indexing an earlier version. Adding to a queue, we make sure we're processing the records independently. I am happy to discuss this further, since this is not the final refinement.
