### ISSUE TITLE
Improve validation in record editor

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1450]
There are several issues with validation in record editor:

* It seems URLs are not validated in the frontend. Maybe they are? format in schema is `uri-reference` which can also be a relative URL (due to `next` compatibility). This will cause issues with curators leaving off the protocol.
* Validation of `required` fields doesn't seem to happen on the frontend
* When putting a wrong URL on the record editor (not holdingpen), the `PUT` fails with a `500` error: https://sentry.inspirebeta.net/inspire-qa/hep/issues/394694/?query=is%3Aunresolved. The download is attempted before validation, but **validation should be the very first thing that happens, otherwise you might get failures in other places due to wrong assumptions (and potential security issues)**
* When saving a record in the holdingpen, no validation happens on the `PUT`, it's a further step in the workflow. But the workflow is never shown (it redirects to the previous page after save), so curators are not aware that something is wrong.

**Comment by harunurhan** [comment]
1. Editor validates on only primitive values. And `uri` or `uri-reference` is not supported, only `url`. So we'll have to add custom validations for those. It can either be baked in to `ng2-json-editor` directly (probably better if they are part of the spec) or configured via `customFormatValidation` from `record-editor`
2. Required fields are always shown by default but we want to keep client side validation lightweight that's why only primitive values are validated on change. But we can call explicit validation when `Save` is clicked on `record-editor` for the whole record if that's helpful.
3. I am not sure If I understood this one correctly. Wrong url like valid but in accessible?
4. Well this is I guess that nature of workflow object because they can be edited on any stage but they don't have to be schema compliant, except just before actual record update/create.

**Comment by michamos** [comment]
3. no, an invalid URL, like `auiebpe` (which is a valid `uri-reference` though). But that's probably a valid `uri-reference` (which needs to be accepted due to legacy). Maybe we should further disallow anything that doesn't match `^(https?://|/api/files/)` in the schema? the only relative URLs are produced by the workflow AFAIK.

**Comment by harunurhan** [comment]
Yeah that regexp sounds good, but tbh `uri-reference` format seems useless to me 😄

**Comment by harunurhan** [comment]
To summarize the discussion we had IRL:
 
- Add `uri` and `uri-reference` for `ng2-json-editor
  - Backend spec: https://github.com/inspirehep/inspire-schemas/blob/ab35f92f667cea0974cb54f717ef6913ba30cf65/inspire_schemas/utils.py#L672
- `PUT /api/holdingpen/<id>` must validate and return validation errors in the format that `ng2-json-editor` expects

**Comment by harunurhan** [comment]
So for this task, we will only do `uri` and `uri-reference` validation:

- We can try to upgrade `ajv` (json-schema validation library that is used) which seem to validate these formats already: https://github.com/ajv-validator/ajv/blob/d580d3e8ac6a467670d68d86e3a39fd661ac8c23/lib/compile/formats.js#L39-L40
- If upgrade causes another issues, we could just formats like we have done for our custom "url" https://github.com/inveniosoftware-contrib/ng2-json-editor/blob/0387e04200960290c6fbe1bdf0c33e5cc4e228e5/src/shared/services/schema-validation.service.ts#L80

We need to double check if `formats` from `ajv` is actually are the same as the spec the backend is using https://github.com/inspirehep/inspire-schemas/blob/ab35f92f667cea0974cb54f717ef6913ba30cf65/inspire_schemas/utils.py#L672

**Comment by harunurhan** [comment]
Looks like the current version of `ajv` that we have, already supports and validates these formats. But after discussing with @michamos we wanted to drop `uri-reference` and use a stricter `pattern` instead

https://github.com/inspirehep/inspire-schemas/pull/409
