### ISSUE TITLE
Add links for identifiers on author profiles

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1517]
@hoc3426 reports that we don't currently link to Google Scholar profiles on author profiles. We have [~200 authors](https://inspirehep.net/authors?sort=bestmatch&size=25&page=1&q=ids.schema%3AGOOGLESCHOLAR) that have such a link. We should take the `value` from `ids` where `schema` is `GOOGLESCHOLAR` and add a link to `https://scholar.google.com/citations?user={value}`. The same holds for Wikipedia [~550 authors](https://inspirehep.net/authors?sort=bestmatch&size=25&page=1&q=ids.schema%3AWIKIPEDIA) that should be linked as `https://en.wikipedia.org/wiki/{value}`.

**Comment by harunurhan** [comment]
@StellaCh are they going to be together with personal websites (under the dropdown)?

**Comment by StellaCh** [comment]
yes exactly.

**Comment by harunurhan** [comment]
Change ui detail serializer https://github.com/inspirehep/inspirehep/blob/18df210fcd86471a53317c639c774994c300797e/backend/inspirehep/records/marshmallow/authors/ui.py#L27 

and add `urls` which should have original `urls` and googlescholar and wikipedia urls appended, with a proper description `{ description: "Wikipedia" or "Google Scholar", value: <full url> }`

https://github.com/inspirehep/inspirehep/blob/18df210fcd86471a53317c639c774994c300797e/ui/src/authors/components/AuthorWebsitesAction.jsx#L51 should probably change to since those aren't only "personal websites" anymore.
