### ISSUE TITLE
don't check etag on get record

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1602]
We need to remove `etags` set and check from `invenio-records-rest`.

From https://inspirehep.zulipchat.com/#narrow/stream/122202-devel/topic/record.20response.20caching/near/219582433

> I think the caching we're doing on records is fundamentally flawed. We're using the record version for the Etag, but things might change without affecting the record version. As Harun already mentioned in the past, we might change the serializers, but also the data itself might change, e.g. citation count or linked proceedings on conference records, which don't affect the record version as their data is kept outside of the record and put into the record when serializing for ES. Paulina got confused by this today, because a Proceedings link for a proceedings she had just created was not appearing on a conference record, but it worked when she cleared her cache.

TECH NOTES:

* Remove this check https://github.com/inspirehep/invenio-records-rest/blob/master/invenio_records_rest/views.py#L803

**Comment by drjova** [comment]
Related issue https://github.com/inspirehep/inspirehep/issues/1534

**Comment by pazembrz** [comment]
*Tech*:
We need a way to distinguish when serializes change. Easiest approach for this would be to md5 whole `records/marshamllow` dir when app starts and keep this value in config.

Easiest way to achieve this would be to use [`checksumdir`](https://pypi.org/project/checksumdir/1.0.5/#description) python module and callculate this hash inside [config_loader](https://github.com/inspirehep/inspirehep/blob/69f4ceeff84c2284b0b3f6b64c7c898301caadda/backend/inspirehep/factory.py#L19) and insert it to [`invenio_config_loader`](https://github.com/inspirehep/inspirehep/blob/69f4ceeff84c2284b0b3f6b64c7c898301caadda/backend/inspirehep/factory.py#L21) kwargs

Now to get proper check/set etag we can
*  use record.revision_id as this is actually an etag (it's only parameter we can set used in etag checking) we can create our own method in inspirehep.record.base.InspireRecord which will just call original one and it will add this md5 at the end of revision_id.
* otherwise we would have to modify every call for check_etag and set etag in invenio_records_rest: [set_etag](https://github.com/inspirehep/invenio-records-rest/blob/f398bab4f4f96607045e753d25aa09bb404e9e42/invenio_records_rest/utils.py#L232) check_etag: [1](https://github.com/inspirehep/invenio-records-rest/blob/f398bab4f4f96607045e753d25aa09bb404e9e42/invenio_records_rest/views.py#L767) [2](https://github.com/inspirehep/invenio-records-rest/blob/f398bab4f4f96607045e753d25aa09bb404e9e42/invenio_records_rest/views.py#L838) [3](https://github.com/inspirehep/invenio-records-rest/blob/f398bab4f4f96607045e753d25aa09bb404e9e42/invenio_records_rest/views.py#L767) and concatenate this md5 with revision_id

**Comment by michamos** [comment]
This is not sufficient, in doesn't take into account dependencies from outside the record. For example changed citation count (which doesn't affect the record in the DB and hence the version number). Or even worse, being logged in or not, which affects the output of the serializer (`can_edit` field).

**Comment by pazembrz** [comment]
Problem is that we are not having any field which stores information if citation count was updated :/ The only way to make it working would be to add citation_count to etag directly... But this will slow down response as we will have to retrieve citation_count from DB...

For logged_in/logged_out user we could extend etag with this information (0/1) just like we update it with md5.
