### ISSUE TITLE
Migrator deleted records

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1666]
On [https://github.com/inspirehep/inspirehep/blob/master/backend/inspirehep/migrator/tasks.py](migrator) we delete `pids` for 
`deleted_records` blindly without checking if the record even exist on hep or has `deleted:True`.  

More details:
https://inspirehep.zulipchat.com/#narrow/stream/122199-ops/topic/bugninja/near/224035593

**Comment by pazembrz** [comment]
Tech Notes:
Instead of [doing this](https://github.com/inspirehep/inspirehep/blob/f9c41f9578cd0c6aea6f4e2dc78236c8b5c34ea9/backend/inspirehep/migrator/tasks.py#L470-L472), deleted record should be loaded and then method `record.delete()` should be called to properly handle deletion. 
Watch out as record which should be deleted might be missing in inspire (process this exception so it won't stop migration).
