### ISSUE TITLE
Gracefully catch HAL push errors

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1777]
`hal push` can throw the exceptions defined here: https://github.com/inspirehep/python-client-sword2/blob/python3/sword2/exceptions.py. The exceptions should be caught and logged gracefully here: https://github.com/inspirehep/inspirehep/blob/9d3ef0776defeed49edd0892c238606d78babd15/backend/inspirehep/hal/tasks.py#L46-L61

**Comment by michamos** [comment]
I'm not sure I understand what this issue is about, but it would be nice to log nice messages from the HAL server rather than the full exception, similarly to what is done currently using https://github.com/inspirehep/inspire-hal/blob/f8c8ccfdbedf14e0ba12521116c2c63ba88b2c54/inspire_hal/bulk_push.py#L108-L117
