### ISSUE TITLE
Skip GROBID author extraction if no author name

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1782]
It might happen that GROBID fails to extract an author name, e.g. https://inspirehep.net/api/holdingpen/2884921. If any author name is missing, the GROBID author data should not be used, and we should fall back to the authors in the metadata.

**Comment by pazembrz** [comment]
Tech:
* Change [this](https://github.com/inspirehep/inspire-next/blob/87337b88aef919a51cfbeee71028f4318a849d7c/inspirehep/modules/workflows/utils/grobid_authors_parser.py#L57-L59) to iterate through all authors and check them. If there at least one empty author then `parse_all` should return None, otherwise build list of authors and return it. 
* [Here](https://github.com/inspirehep/inspire-next/blob/87337b88aef919a51cfbeee71028f4318a849d7c/inspirehep/modules/workflows/tasks/actions.py#L802) We should use parse_all() to get list of authors or None.
* In [here](https://github.com/inspirehep/inspire-next/blob/87337b88aef919a51cfbeee71028f4318a849d7c/inspirehep/modules/workflows/tasks/actions.py#L804) check if authors from record are not None - [related to another small bug](https://inspirehep.net/holdingpen/2891400)
