### ISSUE TITLE
Make validation for dates more strict. 

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#1861]
Dates with this format `2015-7-1` should not allowed and validation should fail. This requires making https://github.com/inspirehep/inspire-utils/blob/b07397c7f7f1f9871d01f3d934f2d4e8678a8c7b/inspire_utils/date.py#L87-L103 raise a `ValidationError` when there is the wrong number of digits, as that is used in the validator: https://github.com/inspirehep/inspire-schemas/blob/9abbda107617b4978dea76b212d24642b7f40a75/inspire_schemas/utils.py#L694.

**Comment by MJedr** [comment]
1. Create a new field for date which will accept only `YYYY`, `YYYY-MM`, `YYYY-MM-DD`.
2. Change all  `format: date` in `date` fields format to the new format in `authors` schema.

**Comment by michamos** [comment]
I don't understand @MJedr's comment. The `date` format validator already accepts partial dates (we use JSON schema draft 4 which doesn't specify what the `format` means, we use `date` to mean a partial date, not an RFC-compliant date). The problem, as written in the issue description, is that the validation is incomplete. We use [`inspire_utils.Partial_date.loads`](https://github.com/inspirehep/inspire-schemas/blob/9abbda107617b4978dea76b212d24642b7f40a75/inspire_schemas/utils.py#L694) for validation. If it doesn't raise, the field is valid. The problem is that `loads` uses [`int`](https://github.com/inspirehep/inspire-utils/blob/b07397c7f7f1f9871d01f3d934f2d4e8678a8c7b/inspire_utils/date.py#L87-L103) to cast the parts of the input string to an `int`, and that doesn't care about leading zeros (`int("05") == int("5") == 5`), so there should be an additional check that the number of chars in the string is as expected.
