### ISSUE TITLE
Handle HAL errors gracefully

### ISSUE THREAD

**Issue by MJedr** [inspirehep/inspirehep#1896]
In HAL when we try to send a new identifier sometimes it happens that the record already exists in HAL and it already has an identifier. In that case, since we didn't create customised exceptions for HAL, we catch every exception and then we check the error message [for example here](https://github.com/inspirehep/inspirehep/blob/f30063c16774758f878e23ae7722b0ab21353e44/backend/inspirehep/hal/tasks.py#L58). This results in thousands of errors on sentry `Unknown error occured. Response headers from the server:`. We should handle this gracefully.

**Comment by MJedr** [comment]
In sword2 there are already some custom [exceptions](https://github.com/inspirehep/python-client-sword2/blob/python3/sword2/exceptions.py) defined

**Comment by oguzdemirbasci** [comment]
Sword2 has predefined exceptions having different error messages for different status codes. This message `Unknown error occured. Response headers from the server` is defined for the response status codes that are not held specifically here https://github.com/inspirehep/python-client-sword2/blob/40c2755d6736d242c0a6a4017feddf7c692f8c22/sword2/connection.py#L299. 

I checked the logs. We have `status 400: bad request` responses for this error with `Paper Id cannot be updated` or `Duplicate Id` messages. `Paper Id cannot be updated` is returned when we try to update a record having a `hal-id` that the server doesn't know. `Duplicate Id` is returned when we try to create a record with a `hal-id` that is already contained by the server. @michamos could you confirm that these are the only cases that we get `Paper Id cannot be updated` and `Duplicate Id` responses? So that we can handle them gracefully.
