### ISSUE TITLE
Don't overwrite records from stale workflows

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#1910]
When we update records through the holdingpen, it's possible that the record has changed in the meantime and the workflow data is stale. We should avoid updating the record in that case and cause an error instead. This affects both record updates on the regular `article` workflow and the new `core_selection` workflow.

**Comment by pazembrz** [comment]
Tech:
* Set `version_id` in all record schemas.
* Add check in update which will compare `version_id` from record.model and incoming data ([simillar to this one](https://github.com/inspirehep/inspire-next/blob/f68516cbf4951cb4c70789e6dbbe5c167ee24c32/inspirehep/modules/workflows/tasks/upload.py#L204)). Version in update HAS TO BE the same as in model.version_id otherwise raise an exception
* Update function should have a flag which when enabled will change behavior of update to ignore missing/wrong version_id (for revert method and for migration)
* [revert](https://github.com/inspirehep/inspirehep/blob/cd4d07ffb77a934f354cdd1da4667b3d7ae63444/backend/inspirehep/records/api/base.py#L635) should call update with flag to ignore `version_id` check
* all migrator functions should call record.update with flag to ignore version check
* On `before_models_committed` signal remove `version_id` from record json blob.
* Update our fork of invenio-records to `v1.3.2` (this version we are currently using)
* In https://github.com/inspirehep/invenio-records/blob/050e7e1836c1d1b225e847f20fd0151a1df519a1/invenio_records/api.py#L114 call https://github.com/inspirehep/invenio-records/blob/050e7e1836c1d1b225e847f20fd0151a1df519a1/invenio_records/api.py#L117 with a copy of obj.json with `version_id` added into json.
* On Next be sure that [when we send record to HEP](https://github.com/inspirehep/inspire-next/blob/f68516cbf4951cb4c70789e6dbbe5c167ee24c32/inspirehep/modules/workflows/tasks/upload.py#L109-L112) we have version_id inside record data. If not then add it (from `obj.extra_data[head_version_id]`)

**Comment by michamos** [comment]
stupid question: can't we just set the `If-Match` header that is already checked in `invenio-records-rest`: https://github.com/inspirehep/invenio-records-rest/blob/c7db3d3d615ccea56e59f921dff78321beee904a/invenio_records_rest/views.py#L880 (which calls https://github.com/inveniosoftware/invenio-rest/blob/master/invenio_rest/views.py#L250-L285) and used by the editor, and modify the `put` method in our fork to disallow `PUT`s that don't have that header? seems a lot easier than inventing a new record field that needs to be checked manually.

Note that internal modifications of the form "read a record from DB, modify it, write back to DB" are already handled automatically by the SQLAlchemy version counter check, so it's really the REST layer, which doesn't start from a DB read in the same transaction, that needs this feature.

**Comment by drjova** [comment]
good point @michamos
