### ISSUE TITLE
Record in WF is missing control_number/acquisition_source.source after merge

### ISSUE THREAD

**Issue by pazembrz** [inspirehep/inspirehep#1967]
Missing control_number
https://inspirehep.net/holdingpen/3083862 Is missing control_number after merge while root had control_number. This key should be always preserved in merged record.

missing acquisition_source.source: 
https://inspirehep.net/api/holdingpen/2852771

**Comment by MJedr** [comment]
The issue with `acquisition_source` is already fixed in #1977.

**Comment by MJedr** [comment]
For 8 records on prod we had incorrect data for sources in db (`control_number` was present). I cleaned them up by removing `control_number` from json.

**Comment by michamos** [comment]
@MJedr could you document what you did exactly? might be useful for the future.

**Comment by MJedr** [comment]
* Since `control_number` should never be part of the `root`, I inspected merging for the record in error state (possible under `workflows/inspect_merge/<pid>` (`control_number` was present in root).
* In merging we take `root` from db, so I had a look at the record for broken workflow - data was wrong there because it contained `control_number`.
* I checked how many records with wrong metadata we have (`select * from workflows_record_sources where json ? 'control_number'`).
* I removed `control_number` from json for records with wrong data:

```
BEGIN;
UPDATE workflows_record_sources SET json=json - 'control_number' WHERE json ? 'control_number';
COMMIT;
```
