### ISSUE TITLE
Avoid creating duplicates on HAL push

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspirehep#2047]
1. We often get `StaleDataError` during HAL push. This happens because the HAL push task races the author disambiguation task which is started at the same time, so it often happen that author disambiguation finishes, and commits the update, between the read of the HAL push and the write to the DB. 

We retry the task in this case: https://github.com/inspirehep/inspirehep/blob/69fa78b8d17f5000883982c1b90b9bdae785d7ed/backend/inspirehep/hal/tasks.py#L44 but the problem is that the HAL push is not idempotent, as the record might have been created successfully on the HAL side, causing a duplicate record to be created when retrying.

The only thing the HAL push writes to the record is the HAL ID, so it seems safe to deal with the exception inside the task and reload the record from DB when it happens. This can't cause missing updates on HAL as the other update will cause a new push in any case. 

2. We might also need to implement a lock system [like for ORCID](https://github.com/inspirehep/inspirehep/blob/69fa78b8d17f5000883982c1b90b9bdae785d7ed/backend/inspirehep/orcid/domain_models.py#L211) to avoid pushing concurrently from two different tasks, as this case is not handled correctly on their side (they said so by email).

**Comment by MJedr** [comment]
**TECH NOTES**
1. [Here](https://github.com/inspirehep/inspirehep/blob/69fa78b8d17f5000883982c1b90b9bdae785d7ed/backend/inspirehep/hal/tasks.py#L58-L59) instead of raising an error reload record from db. Remove `StaleDataError` from autoretry in celery task.
2. For the lock system use [same context manager as in orcid](https://github.com/inspirehep/inspirehep/blob/69fa78b8d17f5000883982c1b90b9bdae785d7ed/backend/inspirehep/orcid/utils.py#L198). Use it after [this line](https://github.com/inspirehep/inspirehep/blob/69fa78b8d17f5000883982c1b90b9bdae785d7ed/backend/inspirehep/hal/tasks.py#L74) (maybe it would be reasonable to move the `distributed_lock` from orcid module to somewhere else). As the lock name use the `hal:{recid}`.
