### ISSUE TITLE
Claiming: As a user claim in your own profile

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2402]
## Own profile

A profile is a user's own if the ORCID they're logged in with matches an ORCID on the author record (this logic is already used for the `edit` button on profiles).

* Display the unclaimed flags like we do for curators on unclaimed papers
* Display the claim menu at the top and the checkboxes on every paper
* Add claim menu on every paper
* For unclaimed papers, the claim menu should contain the options ("This is my paper", "This is not my paper") we currently display to curators but not “Assign to another author”
* For claimed papers, it doesn't make sense to display "This is my paper", it should be grayed out, similarly for the global claim menu at the top in case only claimed papers are selected (this change applies to curators too). When hovering on "This is my paper" in this case, a message "This paper is already claimed" (single paper)"All selected papers are already claimed" (at the top, multiple papers) is displayed.
* The effect of the actions is the same as currently for curators, namely we assign all selected papers to the current author ("This is my paper") or a new author ("This is not my paper").

## Notification messages

The success messages that are displayed on success in the notification depend on the case:
* `This is my paper`: All selected papers will be claimed to your profile.
* `This is not my paper`: All selected papers will be removed from your profile.
* `Move to my profile`: 
    - All claims are allowed: All selected papers will be moved to your profile.
    - Some claims are not allowed: Some claims will be reviewed by our staff for approval.
* For curators, keep the current message

## RT ticket example

```
Title: Claims by user {preferred_author_name} require curator action

The following claims performed by author {author_profile_url} were not handled automatically and require manual intervention.

Names in profile:
* {name_1}
* {name_2}
[etc.]

Already claimed:
* {paper_url_1} is already claimed to {author_url_1} with name "{author_name_1}"
* {paper_url_2} is already claimed to {author_url_2} with name "{author_name_2}"
[etc.]

Incompatible names:
* {paper_url_A} is in profile {author_url_A} and has signature "{signature_full_name_on_paper_A}"
* {paper_url_B} is in profile {author_url_B} and has signature "{signature_full_name_on_paper_B}"
[etc.]
```

https://github.com/inspirehep/inspirehep/issues/2354

**Comment by MJedr** [comment]
To enable claiming:
* check `canEdit` instead of `assignView` [here](https://github.com/inspirehep/inspirehep/blob/f8ddd6e28249bf2ab43aca815ff1e9a2da7cdf7d/ui/src/literature/components/LiteratureItem.jsx#L122) and [here](https://github.com/inspirehep/inspirehep/blob/e4701669ad92e7151bd2350b6a7065a60ca9e032/ui/src/literature/containers/LiteratureSearchContainer.jsx#L93) (or we can change assign view context check)

For the dropdown:
* Create a new action [similar to this one](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/ui/src/authors/components/AssignAction.jsx#L35-L70) and adjust dropdown inside and call it `AssignActionOwnProfile`.   
* We need to pass info if the paper is claimed to the dropdown. Add a function in actions/authors.js which will set true/false value if all papers are non curated (so if all are unclaimed). 
* Grey out the option `"This is my paper”` and display am information "This paper is already claimed" if arePapersUnclaimed is set to false. Call it [here](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/ui/src/authors/containers/AssignOneActionContainer.jsx#L14) and [here](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/ui/src/authors/containers/PublicationsSelectAllContainer.jsx#L18).
* In [literature serach container](https://github.com/inspirehep/inspirehep/blob/e4701669ad92e7151bd2350b6a7065a60ca9e032/ui/src/literature/containers/LiteratureSearchContainer.jsx#L93) add a constant which will map claiming options to strings which will be passed then to assign action container (so assignAuthorView will be mapped to `curator`, `can_edit` and not `assignAuthorView` to `own` and `can_claim` to `different`.
* Pass to `AssignAllActionContainer` and `AssignOneActionContainer`  info which action should be returned (if it’s curator claiming, own profile claiming, different profile claiming) 
* In [`AssignAllActionContainer`](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/ui/src/authors/containers/AssignAllActionContainer.jsx#L20) and [`AssignOneActionContainer`](https://github.com/inspirehep/inspirehep/blob/ba5fe0fdd9aa4daebad985376068487edccf995a/ui/src/authors/containers/AssignOneActionContainer.jsx#L23) check dispatch conditionally either `AssignAction` or `AssignActionOwnProfile` (or other actions for other claim options)
* [Here](https://github.com/inspirehep/inspirehep/blob/f8ddd6e28249bf2ab43aca815ff1e9a2da7cdf7d/ui/src/literature/components/LiteratureItem.jsx#L97) pass also information about the curated relation
