### ISSUE TITLE
Fulltext: send papers to ES using the ingest attachment plugin

### ISSUE THREAD

**Issue by drjova** [inspirehep/inspirehep#2436]
We want to index all of arXiv PDFs and all non-hidden fulltext documents (documents.fulltext is true and documents.hidden is false or documents.source is arxiv). 

We will use the [ingest attachment plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html).

**Comment by MJedr** [comment]
**TECH NOTES**
* first step should be adding new field which will hold fulltext data and defining an [ingestion pipeline](https://www.elastic.co/guide/en/elasticsearch/plugins/current/using-ingest-attachment.html#ingest-attachment-json-ex). It can be done with python [es client](https://stackoverflow.com/a/47000181/13207632)
* then we need to put the attachment. The payload should have the content of the pdf in the field that we declared in the ingestion pipeline, so we'll need to read it before and convert to **base64 string**.

To discuss:
* When to update attachments? On each record update (might be painful, maybe we can check if file was changed since last version of record)?
* Where and when to setup ingestion pipeline? A cli for setting it up might be reasonable.

**Useful resources:**
https://github.com/rahulsinghai/elasticsearch-ingest-attachment-plugin-example
https://github.com/elastic/elasticsearch/blob/master/docs/plugins/ingest-attachment.asciidoc
https://stackoverflow.com/questions/46988307/how-do-you-use-the-elasticsearch-ingest-attachment-processor-plugin-with-the-pyt/47000181#47000181
